services:
  # Laravel App
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clash-board-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - clash-board-network
    depends_on:
      - db
    env_file:
      - ./backend/.env

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: clash-board-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - clash-board-network
    depends_on:
      - app

  # PostgreSQL Service
  db:
    image: postgres:15-alpine
    container_name: clash-board-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clash-board-network

# Docker Networks
networks:
  clash-board-network:
    driver: bridge

# Volumes
volumes:
  postgres_data:
