services:
  # Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clash-board-backend
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/var/www/html
    networks:
      - clash-board-network
    depends_on:
      - db
    env_file:
      - .env

  # PostgreSQL Service
  db:
    image: postgres:15-alpine
    container_name: clash-board-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clash-board-network

# Docker Networks
networks:
  clash-board-network:
    driver: bridge

# Volumes
volumes:
  postgres_data:
